### PR TITLE
Implement the Symbol.species well-known Symbol

### PR DESCRIPTION
**Pull request by pmarkee**
Signed-off-by: Peter Marki marpeter@inf.u-szeged.hu

### CODE REVIEW

**Comment by clover2123** [comment]
@pmarkee 
Some part of this patch is updated in #159 such as symbol `species` and `isConstructor`. Please check it before updating your patch. Thank you.

**Comment by pmarkee** [comment]
Thanks @clover2123 , I will rebase once your patch lands. BTW, `TypedArray.prototype.subarray()` is also related to `Symbol.species`, do you plan to implement that or should it be included in this patch?

**Comment by clover2123** [comment]
@pmarkee Yes, I'll update other TypedArray features related with `Symbol.species` as well. Thank you.

**Comment by pmarkee** [comment]
@clover2123 
Below is a list of all the species-related features and their current status (feel free to correct anything if it's wrong or if I missed something).
Some of the Array builtin functions that use `Symbol.species` do not yet follow the es6 standard, I think it would be better to update those in a separate patch. Is that ok? I also didn't touch the `TypedArray` related parts as we discussed above.
Otherwise the patch is almost ready to be reviewed, I am resolving some test fails currently.

* [SpeciesConstructor](https://www.ecma-international.org/ecma-262/6.0/#sec-speciesconstructor)

| Feature | Status | Comment |
| ------- |:------:| ------- |
| [RegExp.prototype[Symbol.split]](https://www.ecma-international.org/ecma-262/6.0/#sec-regexp.prototype-@@split) | TODO | More related to Symbol.split |
| [%TypedArray%(typedArray)](https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%-typedarray) | TODO | |
| [%TypedArray%.prototype.filter](https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.prototype.filter) | :heavy_check_mark: |  |
| [%TypedArray%.prototype.map](https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.prototype.map) | :heavy_check_mark: |  |
| [%TypedArray%.prototype.slice](https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.prototype.slice) | :heavy_check_mark: |  |
| [%TypedArray%.prototype.subarray](https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.prototype.subarray) | TODO |  |
| [CloneArrayBuffer](https://www.ecma-international.org/ecma-262/6.0/#sec-clonearraybuffer) | TODO | |
| [ArrayBuffer.prototype.slice](https://www.ecma-international.org/ecma-262/6.0/#sec-arraybuffer.prototype.slice) | :heavy_check_mark: | |
| [Promise.prototype.then](https://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.then) | :heavy_check_mark: | |

* [ArraySpeciesCreate](https://www.ecma-international.org/ecma-262/6.0/#sec-arrayspeciescreate)

| Feature | Status | Comment |
| ------- |:------:| ------- |
| [Array.prototype.concat](https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.concat) | :heavy_check_mark: |  |
| [Array.prototype.filter](https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.filter) | TODO | Implement es6 functionality in seperate patch |
| [Array.prototype.map](https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.map) | TODO | Implement es6 functionality in seperate patch |
| [Array.prototype.slice](https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.slice) | TODO | Implement es6 functionality in seperate patch |
| [Array.prototype.splice](https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.splice) | TODO | Implement es6 functionality in seperate patch |

* Promise

| Feature | Status | Comment |
| ------- |:------:| ------- |
| [Promise.all](https://www.ecma-international.org/ecma-262/6.0/#sec-promise.all) | :heavy_check_mark: | |
| [Promise.race](https://www.ecma-international.org/ecma-262/6.0/#sec-promise.race) | :heavy_check_mark: | |

* Native getters

| Feature | Status | Comment |
| ------- |:------:| ------- |
| [get RegExp[Symbol.species]](https://www.ecma-international.org/ecma-262/6.0/#sec-get-regexp-@@species) | :heavy_check_mark: | |
| [get Array[Symbol.species]](https://www.ecma-international.org/ecma-262/6.0/#sec-get-array-@@species) | :heavy_check_mark: | |
| [get %TypedArray%[Symbol.species]](https://www.ecma-international.org/ecma-262/6.0/#sec-get-%typedarray%-@@species) | :heavy_check_mark: | |
| [get Map[Symbol.species]](https://www.ecma-international.org/ecma-262/6.0/#sec-get-map-@@species) | :heavy_check_mark: | |
| [get Set[Symbol.species]](https://www.ecma-international.org/ecma-262/6.0/#sec-get-set-@@species) | :heavy_check_mark: | |
| [get ArrayBuffer[Symbol.species]](https://www.ecma-international.org/ecma-262/6.0/#sec-get-arraybuffer-@@species) | :heavy_check_mark: | |
| [get Promise[Symbol.species]](https://www.ecma-international.org/ecma-262/6.0/#sec-get-promise-@@species) | :heavy_check_mark: | |

**Comment by clover2123** [comment]
@pmarkee 
It seems good, Thanks! 
I'll update missing TypedArray builtin functions that use `Symbol.species` in separate commits.

**Pull request merged**
