### PR TITLE
Implement the class language element part II.

### PR DESCRIPTION
**Pull request by rerobika**
Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by rerobika** [comment]
The basics are done only some minor changes left (error messages, tests) so I think the patch is ready for the review. @clover2123 @ksh8281 Could you please take a look at it? :)

**Comment by rerobika** [comment]
@clover2123 @ksh8281 The patch is done and ready for the review.

**Comment by yichoi** [comment]
@rerobika please rebase it to the master

**Comment by rerobika** [comment]
Note: this PR fixes #234 and #233 as well.

**Comment by yichoi** [comment]
@rerobika rebase please.

**Comment by rerobika** [comment]
@yichoi I've rebased the PR.

**Pull request merged**
