### PR TITLE
Add ES6 RegExp.prototype.exec() method

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
Add ES6 support to RegExp.prototype.exec method.
Also fix regexp-lastIndex.js test in v8.

Signed-off-by: Daniel Balla <dballa@inf.u-szeged.hu>

### CODE REVIEW

**Comment by DanielBallaSZTE** [comment]
Update: 
Checking if a RegExp object really is a RegExp object does not work correctly ATM, working on a fix.

**Comment by clover2123** [comment]
@DanielBallaSZTE The following issue you mentioned is done or WIP now?

> Update:
> Checking if a RegExp object really is a RegExp object does not work correctly ATM, working on a fix.

**Comment by DanielBallaSZTE** [comment]
@clover2123 It was just a sidenote. The issue is definitely a WIP, but it isn't in the scope of this patch, I'll update an another patch. This patch is finished.

**Comment by DanielBallaSZTE** [comment]
Tests that this patch fixes from the skiplist:
`es6/regexp-match-lastindex`
`regexp-lastIndex.js`
`es6/regexp-prototype`
`es6/regexp-replace-lastindex`
`es6/unicode-regexp-unanchored-advance`
`string-slices-regexp`
`regress/regress-2058`

**Comment by DanielBallaSZTE** [comment]
If [this patch](https://github.com/pando-tests/js_vendor_tc/pull/7) lands I'm going to update the vendortests submodule too in this PR.

**Comment by clover2123** [comment]
@DanielBallaSZTE pando-tests/js_vendor_tc#7 is landed. Could you update the vendortest submodule also?

**Comment by DanielBallaSZTE** [comment]
@clover2123 I've updated the PR.

**Pull request merged**
